name: quizzler
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  rflutter_alert: ^1.1.0
  google_fonts: ^1.1.2
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  provider: ^4.3.3
  flutter_spinkit: "^4.1.2"
  shared_preferences: ^0.5.12+4
  back_button_interceptor: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

